name: Alpine Linux Test Workflow

on: [push, workflow_dispatch]

jobs:
  apk-publish:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Get latest apks
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.apk"

      - name: Install dependencies
        run: |
          apk add alpine-sdk openssl

      - name: Import keys
        run: |
          echo $APK_PACKAGE_RSA > ~/.abuild/abuild.rsa
          openssl rsa -pubout -in ~/.abuild/abuild.rsa -out ~/.abuild/abuild.rsa.pub
          echo "PACKAGER_PRIVKEY=\"~/.abuild/abuild.rsa\"" >> /etc/abuild.conf
          cp ~/.abuild/abuild.rsa.pub /etc/apk/keys/
        env:
          APK_PACKAGE_RSA: ${{ secrets.APK_PACKAGE_RSA }}

      - name: Make and sign apkindex
        run: |
          apk index -o APKINDEX.tar.gz *.apk
          abuild-sign -k ~/.abuild/abuild.rsa APKINDEX.tar.gz

      - name: Create README.md
        run: |
          echo -e " # TODO" > README.md

      - name: Cleanup
        run: |
          rm -rf ~/.abuild

      - name: Push to APK repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.APK_SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'iits-consulting'
          destination-repository-name: 'apk-repo'
          user-email: mweya.ruider@iits-consulting.de
          target-branch: main