name: Test RPM release
on: [push, workflow_dispatch]
jobs:
  rpm-publish:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Get latest apks
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.rpm"

      - name: Generate keys
        run: |
          export GPG_TTY=`tty`;
          echo "$GPG_PPA_PRIV_KEY" | base64 --decode | gpg --import --batch;
          echo -e "pinentry-mode loopback \npassphrase ${GPG_PPA_PRIV_KEY_PASSPHRASE}" > ~/.gnupg/gpg.conf
          echo -e "%_signature gpg \n%_gpg_name mweya.ruider@iits-consulting.de" > /root/.rpmmacros
          rpm --addsign *.rpm
          mkdir -p otc\-auth/packages
          mv *.rpm otc\-auth/packages
          cd otc\-auth/packages
          createrepo .
          gpg --detach-sign --armor --default-key "mweya.ruider@iits-consulting.de" repodata/repomd.xml
          gpg --armor --export "mweya.ruider@iits-consulting.de" > KEY.gpg;
          echo -e "[example-repo]\nname=Example Repo\nbaseurl=http://iits-consulting.github.io/rpm-repo/packages\nenabled=1\ngpgcheck=1\ngpgkey=http://iits-consulting.github.io/rpm-repo/KEY.gpg" > example.repo
          cd ~
        env:
          GPG_PPA_PRIV_KEY: ${{ secrets.GPG_PPA_PRIV_KEY }}
          GPG_PPA_PRIV_KEY_PASSPHRASE: ${{ secrets.GPG_PPA_PRIV_KEY_PASSPHRASE }}

      - name: Push to RPM repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.RPM_SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'iits-consulting'
          destination-repository-name: 'rpm-repo'
          user-email: mweya.ruider@iits-consulting.de
          target-branch: main